### ISSUE TITLE
error after adding a game

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#11]
after adding a game to Echelon, I get an error. See attachment. 

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26368461/fb4778f2-3ff1-11e7-9f4a-9ea6f244784f.png)

**Comment by MichaelHillcox** [comment]
Could you get me the exact URL when that happens.

**Comment by wassie** [comment]
it's handled by http://www.XXXX.XX/echelon/settings-games.php

**Comment by MichaelHillcox** [comment]
Alright, this should be fixed.

**Comment by wassie** [comment]
can't confirm this yet because issue #15 is blocking for testing this.
