### ISSUE TITLE
Locked Out!

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#12]
after trying to update the game settings, it wont let me update them and enable XLRstats and chatlog. After several times I get this message and I have to unlock myself thru the database. 

Locked Out!

You have been locked out of Echelon for repeated hacking attempts. This ban is permanent. If you feel that you should not be banned please contact the site admin.

**Comment by MichaelHillcox** [comment]
I'm removing this whole systems

**Comment by wassie** [comment]
are you moving the security part or the plugin part?

**Comment by MichaelHillcox** [comment]
Security part. Sorry that wasn't clear. I'm removing the entire Locked Out shit because it's useless if the original developer just put 6 seconds into making actual security.

**Comment by wassie** [comment]
it does suck if you need to remove the  database line for getting access again :) So totally agreed!

**Comment by MichaelHillcox** [comment]
This has now been removed. I'll be revising the system soon so I'm gunna close this issue 👍
