### ISSUE TITLE
After the first time adding a game, can't change settings

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#13]
After the first time adding a game, can't change settings of the game because it isn't showing in game settings. As you can see the game settings are saved in the database:

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26371999/c4f078b6-3ffc-11e7-8b1f-b1c67b694eea.png)

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26371980/b7acc614-3ffc-11e7-9694-7fb4c35125b5.png)

**Comment by MichaelHillcox** [comment]
I'll look into it :)

**Comment by MichaelHillcox** [comment]
d67faaa should have fixed this issue.

**Comment by wassie** [comment]
great, what file(s) should I replace?

**Comment by slottybon** [comment]
replace the ones that were edited. You can see what changed in which files in every commit: https://github.com/MichaelHillcox/Echelon/commit/d67faaa7d1f07aacf534355c5a47ef2b0d624917
So it'd be:
'actions/settings-game.php' 
and 
'settings-game.php'

**Comment by MichaelHillcox** [comment]
This should all be fixed now so I'm going to close this issue until I get some conformation

**Comment by wassie** [comment]
I confirm that this issue is fixed!
