### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#14]
After your updates in the app directory, I have logged off, upload the app directory and tried to logon again, but get this message:
![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26417225/dc0b8d58-40b8-11e7-819c-997d53d653f4.png)

what am I doing wrong?

**Comment by MichaelHillcox** [comment]
Looks like you've replaced your config.php file with mine... maybe? check and make sure that the config file is set up correctly

**Comment by MichaelHillcox** [comment]
Any update on this? I'm going to close this issue until I get some conformation.

**Comment by wassie** [comment]
looks good, no issues anymore!
