### ISSUE TITLE
admin email

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#16]
after the first install, I don't receive an email with login credentials. Not sure if that has something to do with my hosting environment or that the email isn't send.

**Comment by MichaelHillcox** [comment]
Does your hosting services support emailing from the server and have you got send emails set to yes / true in the config.php file.

**Comment by wassie** [comment]
both questions are answered with yes. the old Echelon did send the email and it is within the same hosting package.

**Comment by MichaelHillcox** [comment]
Then I shall have a look into it for you.

**Comment by wassie** [comment]
it would be helpful if the email was send successfully, it would wright a line in the log file. is that possible?

**Comment by MichaelHillcox** [comment]
Gunna go ahead and close this. I've think i've found what I did wrong.

**Comment by wassie** [comment]
To be able to test if the admin email is send, I deleted all tables and all files. I have downloaded all files from Git, import the sql file in the echelon database and hit the install. After that I see a better looking setup page. Good job!
When I fill in all needed fields and hit the install button, I get an error page.
![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26508155/dfb97b76-4253-11e7-8b76-e79673e2df02.png)
And this is the url that is showing.
http://vipweapons.com/echelonnew/install/index.php?t=done
When deleting the install directory after that and trying to open Echelon url, I get on 404 page.

So I can't confirm if the admin credentials are being send.

**Comment by wassie** [comment]
by the way, when checking the database, I do see several records been added to the ech_config table.

**Comment by MichaelHillcox** [comment]
That's for another issue :P I'm half aware of the issue

**Comment by wassie** [comment]
confirmed that this issue is fixed

**Comment by wassie** [comment]
not sure what the status is of this issue, but I don't get any admin email after first time installation.

**Comment by MichaelHillcox** [comment]
You no longer get an admin email after first install because I've added the password input to the install... No longer a reason to send an email :P
