### ISSUE TITLE
Add deeper integration with B3 Management.

### ISSUE THREAD

**Issue by MichaelHillcox** [MichaelHillcox/Echelon#17]
That. Basically open up echelon a little but to allow more b3 management functionality.

**Comment by wassie** [comment]
what sort of management functionality have you put in?
And is the world player map a part of it?

**Comment by MichaelHillcox** [comment]
The world player map is very much a side project so that is basically at the bottom of the priority list. 
Echelon in it's self only manages the top level basic functionality of b3 so I want to add things like

- being able to live ban people that are currently in the game. 
- Showing a list of players that are in the game.
- Improving the client list to also show is currently online
- Allow editing of more b3 settings that are handled through the database. 

Nothing is set in stone. This is very much a reminder task to look at what can be done.

**Comment by wassie** [comment]
sounds great!
