### ISSUE TITLE
can't read information from chatlogger

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#19]
can't read information from chatlogger. it seems that Echelon can't read the chatlog table :

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26472989/26a0a4ca-41a9-11e7-9516-6a3db1514896.png)

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26473099/c4f313c4-41a9-11e7-8fe7-afefc715c6d9.png)

**Comment by MichaelHillcox** [comment]
Please double check that you've set up a b3 db and that you've entered the correct mysql table names in the settings area.

**Comment by wassie** [comment]
it looks like if I can't choose the chatlog table in you Echelon.

Current Echelon:
![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26500313/bfa99104-4235-11e7-87c1-fe15d000dfe7.png)

Your Echelon:
![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26500353/e02d67fc-4235-11e7-9adc-aaf148a5735a.png)

I think it has something to do with connecting to the B3 database, because I can't list any clients to:
![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26500393/0aa62f0a-4236-11e7-8c8d-459624479fad.png)

**Comment by MichaelHillcox** [comment]
@wassie That should be fixed now. Can you confirm

**Comment by wassie** [comment]
is also waiting for issue #16 for continuing testing.

**Comment by wassie** [comment]
confirmed that it is fixed!
