### ISSUE TITLE
Feedback on new look

### ISSUE THREAD

**Issue by MichaelHillcox** [MichaelHillcox/Echelon#2]
Any feedback on the new look would be awesome. I will continue to update this page with new screenshots. This is the progress i've made so far.

![screenshot](https://i.gyazo.com/30ec280c45f184868643a7b5110f034d.png)

**Comment by slottybon** [comment]
Looks good. How about sans-serif only and no shadows (form elements) or gradients (table header)? I would go with "Trebuchet MS" as a web safe font.

![selection_009](https://cloud.githubusercontent.com/assets/20265856/16714150/f50faa8a-46ba-11e6-9a91-79b56f89ce41.png)

**Comment by MichaelHillcox** [comment]
@slottybon Thanks for the feedback.
Still got lots of work to do with the tables. They are not great pulse tables kinda suck. So I may be looking at replacing them at some point.

I am slowly removing all the gradients too. This is not 2002 anymore. Flat design is the future ( boy how thats going to change haha ). I have changed the font to Roboto. Its the font from android. I am looking at alternatives although Roboto is websafe and Trebuchet is not that nice. Looking for visually pleasing fonts.

**Comment by wassie** [comment]
the design looks fresh and neat! Thanks a lot for all your designing work!

**Comment by MichaelHillcox** [comment]
:heart:

**Comment by MichaelHillcox** [comment]
Thank you everyone that commented ❤️
