### ISSUE TITLE
ech_games db_name is empty

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#20]
after adding a game to Echelon, I have noticed that the db_name is empty in ech_games table. All other fields are having values, except db_name. Is that why I can't choose the chatlog table in chat log plugin page?

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26524120/3d7a104c-4329-11e7-902a-7430b10bb8c3.png)

**Comment by wassie** [comment]
asking the question is answering the question :)
I manually added the db_name into the database, went back to the chat log plugin page, added the mysql table name and name, confirmed and now  I see the chatlog information.
I seems to be that the db_name field isn't adding the value.

**Comment by MichaelHillcox** [comment]
00bc429 Should now allow you to edit the game to be able to add the db_name again. I've check the code and this shouldn't logically be happening but does sometimes. I'm going to do more testing and I've got to restructure the entire game selecting code because it's literal cancer. The noted commit so simple a temp fix until I can fix it properly.

**Comment by MichaelHillcox** [comment]
This should be fixed now.

**Comment by wassie** [comment]
ok, I didn't did a clean install, but if it's necessary again, I will test it.

**Comment by wassie** [comment]
so I have done the clean install, just to test them issues :)

After adding the chatlog table in the chatlogger plugin, I now see that the chat records and also a success message. But I see also an error message. So I'm a bit confused if the adding is successful or not.

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26645713/5de153fa-4639-11e7-8ac1-aa3bd91eae47.png)

**Comment by MichaelHillcox** [comment]
It's loaded the chat messages so I'd have to assume it's worked. I'll have a look to see whats caused the error issue.
