### ISSUE TITLE
navigate in chatlog

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#21]
this is still one of my wishes. is it possible to add the possibility of navigation in chatlines? I can't see how many chatlines are showing, but it would be great if you can go back further with the use of navigation. And even in the personal chatlog of a player. is that possible?

**Comment by MichaelHillcox** [comment]
I'm working on giving plugins the ability to use the built in pagination system but i've yet to find time for this work. I'll be remaking the chat logger plugin soon so I'll add this to the todo list.

**Comment by wassie** [comment]
great!

**Comment by wassie** [comment]
hi Michael, are you still developing Echelon?

**Comment by wassie** [comment]
Great Michael, I can imagen that it is a big project! I really hope you will stick to it and be able to finish it! 

 

Van: Michael Hillcox [mailto:notifications@github.com] 
Verzonden: maandag 14 augustus 2017 23:50
Aan: MichaelHillcox/Echelon <Echelon@noreply.github.com>
CC: wassie <wassie@caiway.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [MichaelHillcox/Echelon] navigate in chatlog (#21)

 

Defintely still on my todo list:  <https://camo.githubusercontent.com/02136d5963a4f3d34b859126a2a2f27fd961afc9/68747470733a2f2f692e696d6775722e636f6d2f4d5276584842512e706e67> 
Unfortuantly the legacy code is taking quite a long time to get into a better state so I'm going to be looking into a better way to continue the project.

**Comment by wassie** [comment]
because the navigation part has a low priority, is it possible to give me the mysql script that gives the chat log table? Now I have UNIX timestamps that I can't convert. And I would like it if I can navigate further back in my chat log.

**Comment by MichaelHillcox** [comment]
Hmm, I'm not 100% sure on what you mean here. What are you trying to achive?

**Comment by wassie** [comment]
the page where the first 100 (?) chat records are showing should be built with a sql query. The timestamp of the chat records in the table are in UNIX format, and the timestamp of those records in the chat log page are in readable format. So that means that I could use the sql query to read the chat log table in a better way. does this clarify a bit?

**Comment by MichaelHillcox** [comment]
Not really... I'm gunna build the chatlog system into echelon because it's basically something everyone uses. I'm not really understand what you are asking from me. Unix time stamps can be very easily converted. Simply Google :) the SQL query to get the is very simple... Something like this `SELECT * FROM chatlogs ORDER BY time_created LIMIT 0,100` that's out of memory.

**Comment by wassie** [comment]
the right select is: SELECT * FROM chatlog ORDER BY msg_time LIMIT 0,100 
The thing is that the outcome is in Unix time format, like: 1492643768

I found an example while using Google:
select FROM_UNIXTIME(UNIX_TIMESTAMP(),'%a %b %d %H:%i:%s UTC %Y');
output will be:
'Wed Feb 05 05:36:16 UTC 2014'

I don't have much experience with SQL to complete this select script. I thought that this script would be already within the Echelon code, because there are 2 pages where the time is already converted:

Client listing:
Name | Client-id | Level | Connections | First Seen | Last Seen
lucky shot | @9093 | Regular | 2461 | Wed, 18/09/13 (02:53) | Sun, 15/10/17 (00:37)

Chatlogger:
id | Name | Type | Message | Time
6703551 | Burbey | ALL | lame | Tue, 17/10/17 (20:40)

I was hoping that I could find those scripts somewhere within the Echelon code........

**Comment by wassie** [comment]
hi Michael, did you find this part of the code somewhere?
