### ISSUE TITLE
Implement a Template engine

### ISSUE THREAD

**Issue by MichaelHillcox** [MichaelHillcox/Echelon#23]
This would be beneficial for making the views a lot cleaner.

**Comment by MichaelHillcox** [comment]
This is going to be hell!

**Comment by slottybon** [comment]
Glad to see you are still working on this. I am rooting for you! :D 

About the template engine. I don't really think it's important and seeing the amount of extra work you get by adding this, I do not think this should be implemented yet?

**Comment by MichaelHillcox** [comment]
It's only mid on my priority list. It's something I want to work on getting done but it's likely to be something done when I rewrite the system.
