### ISSUE TITLE
After logout, perm lockout

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#24]
when I use the logout function in the rightcorner, I get the message that I'm lockout. I have to unlock myself thru database

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26645028/02380d5c-4637-11e7-8ff9-bf3c5129af89.png)

**Comment by MichaelHillcox** [comment]
Does this issue persist?

**Comment by wassie** [comment]
after the clean install its a bit different. It doesn't create a perm locked out, but it has an issue with return url. After logout, the return url is www.DOMAINNAME.com, instead of www.DOMAINNAME.com/ECHELONINSTALLFOLDER

**Comment by MichaelHillcox** [comment]
I'll have a look into it :)

**Comment by wassie** [comment]
logout also means a ban record in the blacklist table. I have to delete the record manually to gain access. And the return url is the same.

**Comment by wassie** [comment]
hi Michael, did you find any time to work on these issues?

**Comment by MichaelHillcox** [comment]
@wassie This has been temp fixed for now but redoing the hack protection is high on my list. Thanks for reporting the issue. I've fixed this as of e56558c

**Comment by wassie** [comment]
I confirm that after logout the user isn't locked out anymore. But the return url could have some 'work'. The return url is missing the directory where Echelon is installed and is going to the root of the domain, with login.php at the end. That gives an 404 error.

**Comment by MichaelHillcox** [comment]
I'll take a look :)

**Comment by MichaelHillcox** [comment]
I've decided! I'm gunna rewrite it so this issue is no longer valid. Thanks for forcing me to look at the code though haha.

**Comment by wassie** [comment]
lol, you're welcome :)
