### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#25]
Is it possible to create a menu item that will show all given !follow commands, by who, time etc, like admin bans?

**Comment by MichaelHillcox** [comment]
Follow? Remind me again what that does

**Comment by wassie** [comment]
the !follow command will add a line in the following table, if the follow plugin is installed. 
The table structure looks like this:
id, client_id, admin_id, time_add, reason

If an admin gives the command '!follow player_id reason_follow' in game while B3 is running, it will add this to this table. 
http://forum.bigbrotherbot.net/releases/follow-users-plugin/

**Comment by MichaelHillcox** [comment]
I'll write a plugin for it :)

**Comment by wassie** [comment]
lol, the plugin is already there. But to show the table lines in Echelon would be great :)

**Comment by MichaelHillcox** [comment]
A plugin for echelon I mean.

**Comment by wassie** [comment]
I see, that would be great!

**Comment by wassie** [comment]
hi Michael, anything new to test yet?

**Comment by MichaelHillcox** [comment]
I've got to admit this has totally fallen off of my priority list. The code base is just a pain in the ass to maintain. I'm going to be going over the entire app in full some time soon to address any issues I find but I think throwing it out into the community is the best way for me to find and fix issues along as being able to extend the application itself.

**Comment by wassie** [comment]
I do understand. To bad tho, it would really be great if those issues would be solved and if there was a stable version of this application. It would also be great if you would get some help. I’m really sorry that I can’t be of any assistance. If I could, I really would help out!

 

Van: Michael Hillcox [mailto:notifications@github.com] 
Verzonden: maandag 25 september 2017 17:30
Aan: MichaelHillcox/Echelon <Echelon@noreply.github.com>
CC: wassie <wassie@caiway.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [MichaelHillcox/Echelon] Feature request (#25)

 

I've got to admit this has totally fallen off of my priority list. The code base is just a pain in the ass to maintain. I'm going to be going over the entire app in full some time soon to address any issues I find but I think throwing it out into the community is the best way for me to find and fix issues along as being able to extend the application itself.

**Comment by MichaelHillcox** [comment]
Done!

(Wiki page here)[https://github.com/MichaelHillcox/Echelon/wiki/Follows-Plugin]

You'll need to pull from the latest version of my code ( thats the one in the commit code above ). This will include the plugin. Make sure to follow the wiki page and once you've done all that simply go to game settings and enable the Following plugin in the plugins area. 

This is a very basic and likely not very well written prototype so I can see how hard and annoying it is to make plugins for echelon... The answer was pretty annoying. Not too hard though. I've been able to also improve the plugin base class so improvements all round! Yay.

Not sure when I'm gunna come back to this but it's in the todo list now.
