### ISSUE TITLE
Few Issues 

### ISSUE THREAD

**Issue by efinst0rm** [MichaelHillcox/Echelon#26]
Hey,

I have found a few issues with current verison.

The biggest one is that after a few clients in the client details will not show up.
Example: 
This is the first client.
![tloglqgcmx8p7jfqplmt](https://user-images.githubusercontent.com/7751074/28750874-a5a0c7ea-74bd-11e7-90f5-731dda7148c5.png)

Last Client 
Will display no info.
![71vp2vhdw1jcf3iz4rb0](https://user-images.githubusercontent.com/7751074/28750876-bc1c316c-74bd-11e7-9b2d-c85ed5a79266.png)

Next minor issues I found.
Undefined variable: query_normal in header.php on line 4
Undefined variable: query_normal in header.php on line 239
Undefined variable: id in clientdetails.php on line 362
Undefined variable: id in clientdetails.php on line 427

Thanks.

**Comment by MichaelHillcox** [comment]
Thanks, when I get some time to look at these I'll get them fixed. I do try to remind people that this system is not yet ready for public use on production servers so try to remember that there will be a lot of issues to come before we get a stable public release.

**Comment by MichaelHillcox** [comment]
Thanks for pointing some of those out. I'm still yet to completely fix all of the query logic but I've been able to knock off a few of those issues. As for the two photos you've put. I've not been able to reproduce the issue on my end. Although I can see the issue but it won't be fixed for quite some time. I'm gunna go ahead and close this issue but I will come back to it when I do the next sweep of refactors.
