### ISSUE TITLE
white screen after installation 2.1.0.1 Alpha

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#27]
hi,

I just used the latest version 2.1.0.1 Alpha for a clean install to test the last fixed issues. These are the steps taken:
1. create a database table
2. create a database user
3. import echelon.sql
4. upload all files thru ftp
5. run the installer and fill in all credentials

After this last step while saving, a white screen is showing. When I check the database in table ech_users I can see that the created Echelon user in step 5 is saved. The strange thing is that the ip field is NULL, while in other installations of Echelon this field is filled with an ip. 

I have tried to clear the install folder after step 5, but nothing different happens. Still a white screen and also no email with admin credentials.

I also noted that there is a config.tmp file in the app directory. Not sure if that supposed to be, but deleting it won';t change the above situation.

What am I doing wrong?

cheers
Wouter

**Comment by MichaelHillcox** [comment]
There should be a config.php not just a config.tmp if this is the case then I'll have it fixed soon.

**Comment by wassie** [comment]
yes, the config.php file is there and the config.tmp.php file is there too.

**Comment by MichaelHillcox** [comment]
Then, I'm not sure. What link do you see the white screen on? and what php version are you using?

**Comment by wassie** [comment]
install/index.php?t=done is the link.
Can't see anything special in the source too, except some html of course.

I'm using PHP5.4 on this domain.

**Comment by MichaelHillcox** [comment]
so you've tried going to /index.php instead of install/index.php
I'll rerun the install on my main system and see how things go. :D

**Comment by wassie** [comment]
I have installed it only by /install. the return link is after setting things like database, database user etc. after hitting the button, the return link is install/index.php?t=done

**Comment by MichaelHillcox** [comment]
@wassie Thats all fixed for you now and I've also added the option to delete the install dir as well as improved the default config a bit 👍 

Turns out for you it was a white screen but for me it was a error screen. In the future could you ensure that your servers php.ini or other such php config has errors shown so you can give me a more helpful error screen than just a white page 😄

**Comment by wassie** [comment]
sorry for the inconvenience, but my hosting company doesn't allow me to access the php.ini file. But I will ask them if they can change that for me of course!

I will download the latest version of the code and test it again 👍

**Comment by wassie** [comment]
So I have just tested the latest installation again with these steps:

1. create a database table
2. create a database user
3. import echelon.sql
4. upload all files thru ftp
5. run the installer and fill in all credentials
Nice to see that its going to be possible to delete the install folder thru the browser! But this is also causing a new problem. After hitting that button I'm getting
"Fatal Error! You have already installed Echelon. Please delete this page. BUTTON: Find Home, another BUTTON: Go back" Both the message and the buttons are showing in this page: /install/index.php?del=
After manually deleting the install folder, I get a white screen again, to bad without any errors showing. See also attachment.

Of topic, can you create a logfile or maybe a logtable for those PHP errors? Maybe that can help this a bit??
![2017-10-03_17-58-04](https://user-images.githubusercontent.com/17354054/31139775-e108981a-a872-11e7-910b-6727fbdfd374.png)

**Comment by MichaelHillcox** [comment]
If you can provide me with your apache's error log or just an error screen by enabling errors to show on you php instance then I can get this fixed.

**Comment by wassie** [comment]
my Apache's error log is empty. I have asked my hosting company to higher up the php.ini errors

I also tried the installation in a different browser, but still the same.
I also tried to manually remove the install folder, but still the same. 
at the end I'm getting an error page. When I'm trying to go to the homepage of Echelon with or without index.php, I'm getting a http error 500

**Comment by MichaelHillcox** [comment]
Yeah, it means something is wrong with php and php is throwing an error as to whats gone wrong but your hosting isn't showing it due to the errors being disabled. I'm not able to reproduce your issue after my fix so I'm not 100% sure on how to fix it thus far.

**Comment by wassie** [comment]
tried some last thing and I think I found something. At another domain I have PHP 7 running. Tried to install it at that domain, and after deleting the install folder, it shows the login screen. So this issue is related to PHP 5.4 and can be solved with using PHP 7.

Now I will continue testing the other issues!

**Comment by MichaelHillcox** [comment]
Ah, yes. I've moved us onto php7 only for now. I might back support it after the first release.
