### ISSUE TITLE
After adding chatlogger table, succes and error in one message

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#28]
"Success! The chatlog settings have been updatedError! The chatlogs table you asked for does not exist, please select a real table."

This message appears when selecting the chatlog table. Below this message I see the chatlog with the latest chat messages in it, so it seems to work correct.

**Comment by wassie** [comment]
same as issue #20

**Comment by MichaelHillcox** [comment]
To confirm, You've entered the b3 database details inside the config and not through the setup because It's been removed from database now.

**Comment by wassie** [comment]
yes,  I did!

**Comment by MichaelHillcox** [comment]
I'll investigate :)

**Comment by MichaelHillcox** [comment]
Hmm, I'm struggling to find why this is happing for you. Are you sure the db table name is correct?

**Comment by wassie** [comment]
yes, because after that the chat log is showing. The strange thing is that first it is success and after it, it shows the error. If you check the message at the top of this issue, you can see that there is no space between the word 'updated' and 'error'. So my guess is that the success message also gets the error in the same part of code. just my 2 cents :)

**Comment by MichaelHillcox** [comment]
I'll investigate :)

**Comment by wassie** [comment]
thanks! Did you also see my comment about the sql script? that would help me a lot!
