### ISSUE TITLE
Can't get it working ...

### ISSUE THREAD

**Issue by Skillz7z** [MichaelHillcox/Echelon#29]
Hello sir 
Am so excited for this ... but i can't get echelon working idk why 
I have php 5.6 
mysql and apache2 installed 
I used the install script and it says installed and give a page for 3 options deleting install folder edit your profile or go to main page 
all of them does not work 
Look here 
That's when i load my page 
https://echelon.xtreme-gaming.co/xtremegaming/
Can you help me please ?

**Comment by MichaelHillcox** [comment]
Current version is only php7. I'd suggest enabling php errors so you can show me the physical error. But I'm pretty sure it's just that your using php5.6 I might modify the code back to only use php5.6 but we'd be losing functionality a little.

**Comment by Skillz7z** [comment]
Well sir then you have to edit the readme cuz it says it support 5.6 xD i was so happy cuz it does 
But can't you make it support both ? or its not possible ?

**Comment by Skillz7z** [comment]
One more thing this is the error am getting 
Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in /*****/inc.php on line 43

**Comment by Skillz7z** [comment]
Well sir you know whats the real problem here ?
If you want use php7 then you will not be apple to use xlrstats webfront cuz of cakephp

**Comment by Skillz7z** [comment]
Close this post 
It worked with php7
