### ISSUE TITLE
Database error 

### ISSUE THREAD

**Issue by Skillz7z** [MichaelHillcox/Echelon#34]
Warning: require(app/classes/B3Database.php): failed to open stream: No such file or directory in /****/app/bootstrap.php on line 148

Fatal error: require(): Failed opening required 'app/classes/B3Database.php' (include_path='.:/usr/share/php') in /****//xtreme/app/bootstrap.php on line 148

**Comment by MichaelHillcox** [comment]
Thanks :D. The version of the code you are using is very unstable. I wouldn't suggest using it on a public domain
