### ISSUE TITLE
Totally don't understand

### ISSUE THREAD

**Issue by Skillz7z** [MichaelHillcox/Echelon#36]
What i have to write inside the index.html exactly .... 
i really don't understand ................................. 

and why is it looking like this ??
http://prntscr.com/i1wknl

**Comment by MichaelHillcox** [comment]
Opps, I completely forgot about the install :P

**Comment by MichaelHillcox** [comment]
I'll add this to the wiki but to help secure the system a little bit more we now have a public directory. What that does is allow us to lock off all of the other directories like, `app/` for instance. This means no matter what people can't go through and see all of the config data etc. This brings me closer to being able to store more sensative data inside files that are out of the accessable scope of the web server. 

To make this work you are going to need to change your Nginx / Apache config.
## Nginx
```
// Change your root to the new /public 
server_name echelon.example.com;
root /webserver/echelon/public;
```

## Apache 
```
DocumentRoot "/webserver/echelon/public"
ServerName echelon.example.org
```

If you are using it in a subdirectory so something like `example.com/echelon/` then you will need to change your Nginx or Apache config to make it so when you are at `/echelon/` it will set the documentRoot or root( for nginx ) to `/echelon/public/` By no means should you ever use `example.com/echelon/public` for the actual working website.

**Comment by MichaelHillcox** [comment]
@Skillz7z Sorry about that, It was a complete oversite while I was making a lot of changes to the core of the app.

**Comment by Skillz7z** [comment]
No problem dude you are the best :)
