### ISSUE TITLE
Some issues you need to know 

### ISSUE THREAD

**Issue by Skillz7z** [MichaelHillcox/Echelon#37]
Well dude you have many problems over here 
Sorry i can't follow your form for reporting problems but i will describe for you everything

First you have permission problems in install/index.php 
and i thought its about chown -R www-data:www-data /*******
		/* Create log file
		if( !file_exists($echelon_dir."app/.bin/") ) {
			mkdir($echelon_dir . "app/.bin", 0777, true);

		    if( !file_exists($echelon_dir . "app/.bin/log.txt") )
		        file_put_contents($echelon_dir . "app/.bin/log.txt", "");
		}*/

Ok i commented that line but next issue is wrong directory for require '../app/classes/LegacyDatabase.php';
it has to be like this '../../app/classes/LegacyDatabase.php';

after you do that it says Config file does not exist 
i think you missed with directories dude xD 

Am going to fix these stuff and see what i will got also btw i get this 
Route xtreme doesn't exist in this scope
is it normal ? its inside the public folder

**Comment by MichaelHillcox** [comment]
`Route xtreme doesn't exist in this scope` Follow my instructions for subdirectories. You need to point the root at the public file. Not navigate to public.

As for file perms. Thats you you dude :P I can't make your server have the right perms for a folder. 

I'll look at the LegacyDatabase one. What directory is that in?

**Comment by Skillz7z** [comment]
require '../../app/classes/LegacyDatabase.php';
$file_read = '../../app/config.tmp.php';
if( !file_put_contents("../../app/config.php", $tmp) )
These are inside the install/index.php
Now am getting 
The requested URL /xtreme/public/login was not found on this server.

**Comment by MichaelHillcox** [comment]
`The requested URL /xtreme/public/login was not found on this server.` This isn't a issue of mine. You need to make sure public is the root in the webserver config. You need to make sure /xtreme/public is the route so you would navigate to /xtreme/login

**Comment by MichaelHillcox** [comment]
Pull a new version of my code. That'll fix your directory issues but you need to look at how your webserver is configured for the /public domain

**Comment by Skillz7z** [comment]
i reinstalled everything and done the up things 

well i changed the whole config of apache2 to DocumentRoot /***/echelon/public

and now i get this https://echelon.xtreme-gaming.co/login

**Comment by MichaelHillcox** [comment]
Add this line to your apache config 
`DirectoryIndex index.php`

**Comment by Skillz7z** [comment]
You mean inside apache2.conf ?

**Comment by MichaelHillcox** [comment]
Yeah

**Comment by Skillz7z** [comment]
Already done it and still not working 


`<IfModule ******>
	<VirtualHost *******>
		DocumentRoot /***************/public
		ServerName echelon.xtreme-gaming.co
                DirectoryIndex index.php
		LogLevel warn
		ErrorLog ${APACHE_LOG_DIR}/*********log
		CustomLog ${APACHE_LOG_DIR}/*******log combined
		DirectoryIndex index.php index.html
		RewriteEngine on
		SSLCertificateFile /********************.pem
		SSLCertificateKeyFile /********************pem
		Include /********************.conf
	</VirtualHost>
</IfModule>`

**Comment by Skillz7z** [comment]
Already done but did not work

**Comment by Skillz7z** [comment]
and btw i got 3 guys trying to understand the part where u says about if am using directories inside the subdomain and no one understood i think you have to provide for me some examples xD

**Comment by MichaelHillcox** [comment]
You got a discord / teamspeak / other?

**Comment by Skillz7z** [comment]
Discord yes

**Comment by MichaelHillcox** [comment]
add me :P https://mikey.pro/?p=MiKeY#3704

**Comment by Skillz7z** [comment]
Done
