### ISSUE TITLE
Setting up new games error.

### ISSUE THREAD

**Issue by efinst0rm** [MichaelHillcox/Echelon#39]
Hi,

So I decided to test this "Now more stable than ever" build. After getting everything setup I added a game and then followed to add the db info and id in config.php.

 Now i get this error
`B3 Database Connection Error: (#2005) Unknown MySQL server host 'G' (2)`

I know the DB info is correct since it works on my other install / checked the b3 config.

Thanks.

**Comment by MichaelHillcox** [comment]
Unknown Server host 'G' Fuck, thats an intresting one. Can you provide me with a full stack log from php, this means i'll need the last 30 ish lines of your error.log ( apache or nginx ).

Could you also redact your db password and send me a copy of your config.php. Feel free to DM me this info if you'd prefer. You can get me at any of my socials at mikey.pro

**Comment by efinst0rm** [comment]
Hey sorry for the late replay.

https://gist.github.com/efinst0rm/e94aa8d43dc6d5a38c5a8afb017d75a2

https://gist.github.com/efinst0rm/6116ec84403adf8aceffb62838641ada

**Comment by MichaelHillcox** [comment]
No worries. What php version are you using?

**Comment by efinst0rm** [comment]
I actually had to update my php since it said it required 7.0 so I'm running 7.1.3

**Comment by efinst0rm** [comment]
Little update if I hard code the DB into the bootstrap.php   ($db = B3Database::getInstance) it will work perfectly fine.

**Comment by MichaelHillcox** [comment]
This needs investigating
