### ISSUE TITLE
Link isn't right

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#4]
after the installation of version v.2.0b.2, a link 'how to use Echelon guide' is been showing in the 'What do I do next?' part. This link isn't working and gives an error

**Comment by MichaelHillcox** [comment]
Does it direct to a local site or go to echelon.b3 something something?

**Comment by wassie** [comment]
I can't reproduce that again, but I think it's linking to something like echelon.b3....

**Comment by MichaelHillcox** [comment]
Fixed https://github.com/MichaelHillcox/Echelon/commit/f0c1e569b8157b8b94fd89cc7deecad6633a8b90
