### ISSUE TITLE
Echelon not installing

### ISSUE THREAD

**Issue by Explosive12** [MichaelHillcox/Echelon#44]
I have followed everything but after pressing install its showing like this :

**This page isn’t working
echelon.coolpings.ga is currently unable to handle this request.
HTTP ERROR 500**

Maybe the problem with this caz I dont know how to rewrite URL etc

**DocumentRoot "/webserver/echelon/public"
ServerName echelon.example.org
<Directory "/webserver/echelon/public">
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule . index.php [L]
</Directory>**

**Comment by MichaelHillcox** [comment]
Looks like you've just kept me default example urls. You need to change the `DocumentRoot` to where your echelon has been put on your server. You need to change `ServerName` to `echelon.coolpings.ga` and you need to change your `Directory` to match the `DocumentRoot`

**Comment by Explosive12** [comment]
Sir , Where I have to change this things ? in .htaccess or any other files ?? 
Sry I am new to this things

**Comment by Explosive12** [comment]
@MichaelHillcox  Waiting for the reply :|

**Comment by MichaelHillcox** [comment]
I very clearly explained what you need to do.

**Comment by Explosive12** [comment]
@MichaelHillcox  
Sir , I am asking that where I need to add these lines ? Which file ? for example .htaccess etc

**Comment by MichaelHillcox** [comment]
Oh, Thats simple :P You want to put it in your apache config file. Not 100% sure on where it will be but somewhere in `/etc/apache2/` do some googling

**Comment by Explosive12** [comment]
Its Still showing like this after Press INSTALL but the tables have created in the phpmyadmin :/
```
This page isn’t working
coolpings.ga is currently unable to handle this request.
HTTP ERROR 500

```

**Comment by MichaelHillcox** [comment]
What php version are you running?

**Comment by Explosive12** [comment]
7.1

**Comment by MichaelHillcox** [comment]
Send me an extract from your error.log and your access.log... The last 300 lines if possible.

**Comment by Explosive12** [comment]
Searching for them .. I will send soon :P

**Comment by Explosive12** [comment]
[access.log](https://github.com/MichaelHillcox/Echelon/files/1775992/access.log)
[error.log](https://github.com/MichaelHillcox/Echelon/files/1775993/error.log)

**Comment by MichaelHillcox** [comment]
Thanks for that. I've removed your links because of the ip's being shown but I've seen them :P 
Right, looks like somethings wrong with the querying. That would mean something like your database has been setup wrong.

**Comment by MichaelHillcox** [comment]
I've figured it out and it will be fixed. Thanks for letting me know.
