### ISSUE TITLE
Text thing v.2.0b.2

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#5]
after login (for the first time) I have noticed a spelling mistake. In the welcome line '.........now all you need to do is good to the 'Echelon' tab in the.......' the word 'good' should be 'go'.

**Comment by MichaelHillcox** [comment]
Thanks, I'll get that fixed 👍

**Comment by MichaelHillcox** [comment]
Fixed, Also update your config file to match the one on the github repo. You're on an old version by the look of things.
