### ISSUE TITLE
php7.2 error

### ISSUE THREAD

**Issue by AlexanderCurl** [MichaelHillcox/Echelon#50]
`What URL did this happen on`
- <DOMAIN>/server-settings

`Description of the issue`
- Unable to create new database table ech_games, after addeda gameserver, and the picklist remains empty.

`Does it happen every time?`
- [X ] Yes 
- [ ] No 

`Please include a pastebin of the php error in full if one was displayed`
- https://pastebin.com/2sqqBx6g

`Please provide your environment information ( Please note, if you have given me this before then link to your past issue if nothing has changed )`

- OS: 
- HTTP Server (Apache, Nginx, etc ): nginx
- PHP Version (PHP 7 and up): PHP 7.2
- MySQL Version: MariaDB 10.2.14

**Comment by MichaelHillcox** [comment]
I'm pretty sure I know what this is. If you wanna try this version of the code https://github.com/MichaelHillcox/Echelon/tree/0e4f3195e032b166d7eeeee3dbdf567dec83e30e and let me know how it goes. 

This version is still in an unstable continual development state and I'm yet to fix a lot of the existing issues. Thank you for you issue report :D

**Comment by AlexanderCurl** [comment]
Im gonna check it out now.

**Comment by AlexanderCurl** [comment]
Nop, still the same.
