### ISSUE TITLE
Rewrite router / implement vendor

### ISSUE THREAD

**Issue by MichaelHillcox** [MichaelHillcox/Echelon#57]

**Comment by wassie** [comment]
hi, are you still developing this project? Is it already stable enough to try out?

**Comment by MichaelHillcox** [comment]
I've currently got a stack of on going project higher than myself so I'm trying to work my way through it. It's why i've started closing some less important issues. I really want to get this project to a stable state so I can do minimal bug fixes over time so Echelon is slowly going up the priority list but it's got so much legacy code that it's just hell to work with... 

I will be focusing on this project again but not for a little while unfortuantly... 😞
