### ISSUE TITLE
Navigation issue in v.2.0b.2, no Echelon tab showing

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#6]
there isn't a Echelon tab in 'navigation above'. I see only 'Home' and 'Admin'. That means that I can't go any further in testing Echelon because I can't setup the link to the B3 database.

**Comment by MichaelHillcox** [comment]
Are you using a Admin account? Is this before or after installing? Anymore info into how you go to this point. I need some more info on this one :)

**Comment by wassie** [comment]
yes, I'm using an admin account. This is after installing and just after deleting the install directory with ftp. After that I activated the admin email and then I login as admin. I hope this printscreen will help:
![2017-01-31_18-58-19](https://cloud.githubusercontent.com/assets/17354054/22477694/51589180-e7e7-11e6-9a92-23070e469ff2.jpg)

**Comment by MichaelHillcox** [comment]
I'll check it out. Thanks :)

**Comment by wassie** [comment]
hi Michael, did you made any changes yet that I can test?

**Comment by MichaelHillcox** [comment]
@wassie Does your profile have permission to clients? if not then you won't be able to see them. The nav is restricted by your permission set. Make sure you have clients in that permission set. ( this goes for the rest too. )

**Comment by wassie** [comment]
@MichaelHillcox what do you mean by permission to clients? After the first setup of Echelon, as a new install, the menu suggest that I could access and/ or add B3 profiles from the admin menu item. But I still can't use that menu item (B3 profiles) and therefor I can't setup any games. I have tried this in Firefox and in Chrome. With the old Echelon 2 I can add a new game server and fill in all B3 settings. In this version (2.1.0.1 Alpha) that isn't possible.

**Comment by wassie** [comment]
if I try to click the B3 profiles menu item, it navigates to the 'My profile' area.

**Comment by MichaelHillcox** [comment]
@wassie https://github.com/MichaelHillcox/Echelon/blob/master/echelon/app/views/global/header.php#L101 this line shows why the menus are not showing up for yourself. For some reason, it would seem that you account is not an administrators.

**Comment by MichaelHillcox** [comment]
@wassie https://github.com/MichaelHillcox/Echelon/blob/master/echelon/app/views/global/header.php#L184 This is why the b3 profile does not work. It's not yet a thing :P

**Comment by wassie** [comment]
@MichaelHillcox how can a admin account not be an administrator? that is strange, specially when the account is created for the first time and the only account. 
When I check the database, ech_users, the admin user is in ech_group 2. Does that help?

**Comment by wassie** [comment]
hi Michael, did you made any progress with this issue? Can I see somewhere in the database if the admin account has the proper rights? I would love to work with the new Echelon!

**Comment by wassie** [comment]
hi Michael, any progress on developing Echelon? I'm really curious to the result!

**Comment by MichaelHillcox** [comment]
@wassie Thank you so much for pointing this out to me. This has now be fixed. I had shitty logic going on her but it's now fixed ❤️  you're awesome. Thanks for testing

**Comment by MichaelHillcox** [comment]
@wassie as for progress. It's slow but I'm trying to get some of the issues fixed now :)

**Comment by wassie** [comment]
@MichaelHillcox , I really appreciate all your work! Glad you still got this project in your scope!

Did you release a new beta version that I can test to confirm if the issues are solved?

**Comment by MichaelHillcox** [comment]
Because of how unstable this system is ( as I've been finding out ) I'm not going to open up any official releases but you can go here https://github.com/MichaelHillcox/Echelon/tree/6334236210ceee9501ca2d3bc4f76e77b8f5166e and click on `Clone or Download` and download the zip. If you've already got the bugged version set up then you should just be able to do a drag and drop upgrade.

**Comment by wassie** [comment]
so no database changes at all? And by drag and drop you mean with ftp uploading files and overwrite the new ones, right?

**Comment by MichaelHillcox** [comment]
Yeah, also no database changes.

**Comment by wassie** [comment]
thanks, will give it a shot and let you know any issues!

**Comment by wassie** [comment]
this issue can be closed. I confirm that there is a navigation bar in the header! Good job!
