### ISSUE TITLE
Changing User Permission

### ISSUE THREAD

**Issue by efinst0rm** [MichaelHillcox/Echelon#9]
When changing user permission / admin level from clientdetails.php you will get a "Hack Attempt Detected".

**Comment by MichaelHillcox** [comment]
I've removing that entire system. Are you running on 2.1 or 2?

**Comment by efinst0rm** [comment]
I'm running 2.1.0.1.

**Comment by efinst0rm** [comment]
Quick update if you look at line 263 in clientdetails.php and change. `<button type="submit" name="level-sub" class="btn btn-default">Change Level</button>` to`<input type="submit" name="level-sub" class="btn btn-default" value="Change Level" />` The form will then work just fine.

**Comment by MichaelHillcox** [comment]
@efinst0rm Thanks for the heads up :) Fixed: https://github.com/MichaelHillcox/Echelon/commit/f0c1e569b8157b8b94fd89cc7deecad6633a8b90
